name: Build android

on:
  push:
    paths:
      - 'shared/**'
      - 'composeApp/src/androidMain/**'
      - 'composeApp/src/commonMain/**'
      - 'androidApp/**'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '*.gradle.kts'
      - 'gradle.properties'
      - '.github/workflows/build-android.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.2.0
        with:
          cache-disabled: false
      - name: Write google-services.json
        run: echo '${{ secrets.GOOGLESERVICESJSON }}' > androidApp/google-services.json
      - name: Build
        run: chmod +x ./gradlew && ./gradlew :androidApp:build
